import time
import json
from serpro_provider import ConsultaNFe
from get_dv import get_dv

# cod_nf generated by linear regression
target_cod = 47467903

# quantity of items between target (target in the middle)
quantity = 100

# limit of requests per second
requests_per_second = 3

initial_list = []
final_list = []
output_list = []


serproProvider = ConsultaNFe(
    'SdQXuO2HTQc8xRBsc2PZxvptYWAa', 'ikkizWvRFdXvS4sDWMrxEqIrw3Ua')


def checkKey(chave):
    resultado = serproProvider.consulta(str(chave))
    return resultado


for i in range(1, quantity + 1):
    initial_list.append(
        '43220107857168000248550020000100601'.__add__(str(target_cod - i)))

initial_list.append(
    '43220107857168000248550020000100601'.__add__(str(target_cod)))

for i in range(1, quantity + 1):
    initial_list.append(
        '43220107857168000248550020000100601'.__add__(str(target_cod + i)))


for chave in initial_list:
    resposta = get_dv(chave)
    final_list.append(chave + resposta)


final_list.append('432201078571680002485500200000997514')


for chave in final_list:
    resposta = checkKey(chave)
    output_list.append({"chave": chave, "resposta": resposta})
    if resposta:
        print(f"Consulta para chave {chave} bem-sucedida")
    else:
        print(f"Erro na consulta para chave {chave}")

    time.sleep(1 / requests_per_second)


with open('respostas.json', 'w') as arquivo_json:
    json.dump(output_list, arquivo_json)


print("Process finished")
